# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Upload to Amazon S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.19.0
        env:
          BUCKET: ${{ secrets.BUCKET_ADDRESS }}

      - name: Run npm install & build website
        run: |
          npm install
          cd photo-upload-website && npm run build
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-east-1

      - name: Copy files to the test website with the AWS CLI
        run: aws s3 sync photo-upload-website/dist ${{ secrets.BUCKET_ADDRESS }} --delete

      - name: CDK Deploy
        run: |
          cd cdk
          npm install
          npm run deploy --BUCKET_NAME=${{ secrets.BUCKET_NAME }}